Задачи раздела №2
js-tasks-ru/jsbasic-20210621_vitalymihale pull request #2
Opened 2021-06-25 09:00 UTC by VitalyMih

2021-06-25 09:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-25 20:49 UTC, SinimaWath requested changes

2021-06-25 20:49 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (Boolean(str) === false) {
Это условие можно упростить до:
```
if (!str) {
  return '';
}
```

2021-06-25 20:49 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  } else {
Не стоит писать, else, когда в условии выше есть уже return. То есть такой код можно переписать на:
```
if () {
  return '';
}

...
```

2021-06-25 20:49 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  } else {
Давай уберем тут else

2021-06-26 05:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-27 12:47 UTC, SinimaWath requested changes

2021-06-27 12:47 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return Boolean(name) === true && name.length >= 4 && name.includes(' ') === false;
Boolean(name) === true - не привычная запись для JavaScript, в мире разработке.

тут любят писать: `!!name `

2021-06-27 12:47 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return str.toLowerCase().includes('1xbet') === true || str.toLowerCase().includes('xxx') === true;
includes - уже возвращается true/false, можно не писать `=== true`. Так как результат операции `||` у тебя будет true или false

2021-06-27 15:31 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-27 15:35 UTC, VitalyMih commented on 1-module/2-task/index.js
> +  return Boolean(name) === true && name.length >= 4 && name.includes(' ') === false;
Исправил. Также исправил 
`name.includes(' ') === false` 
на 
`!name.includes(' ')`

2021-06-27 15:35 UTC, VitalyMih commented on 1-module/4-task/index.js
> +  return str.toLowerCase().includes('1xbet') === true || str.toLowerCase().includes('xxx') === true;
Исправил

2021-06-27 17:37 UTC, SinimaWath approved these changes

2021-06-27 17:37 UTC, merged